Add watch mode
Distinguish watch mode from preview.

Took out XDG stuff, but viewers are currently hard-coded.

diff --git a/src/mdrender b/src/mdrender
--- a/src/mdrender
+++ b/src/mdrender
@@ -2,17 +2,20 @@
 
 # Exit codes
 EXIT_SUCCESS=0
-EXIT_MISSING_MDFILE=1
-EXIT_MISSING_FORMAT=2
-EXIT_BAD_FORMAT=3
-EXIT_PANDOC=4
-EXIT_BAD_CLEANUP=5
+EXIT_MISSING_MDFILE=255
+EXIT_MISSING_FORMAT=254
+EXIT_BAD_FORMAT=253
+EXIT_PANDOC_ERROR=252
+EXIT_BAD_CLEANUP=251
+EXIT_BAD_OUTDIR=250
+EXIT_NO_VIEWER=249
+EXIT_BAD_VIEWER=248
 
 PROGNAME=$(basename $0)
 
 # Default path for temp materials. Use mktemp to find out where this is.
-TMP_DRYRUN=$(mktemp -u)
-TMP_BASE=$(dirname ${TMP_DRYRUN})
+TEMP_DRYRUN=$(mktemp -u)
+TEMP_BASE=$(dirname ${TEMP_DRYRUN})
 
 # This is the location of pandoc template contents.
 PANDOC_DIR=$HOME/.local/share/pandoc
@@ -20,14 +23,14 @@ PANDOC_DIR=$HOME/.local/share/pandoc
 print_help()
 {
 	cat <<- EOF
-	$PROGNAME: Render a document from a markdown file.
+	$PROGNAME: Render a markdown document with Pandoc.
 
 	Formats:
-	- 'note': PDF document suitable for informal documents.
-	- 'beamer' PDF slides using Beamer.
-	- 'html': Standalone HTML document.
+	  - note: PDF document suitable for informal documents.
+	  - beamer: PDF slides using Beamer.
+	  - html: Standalone HTML document.
 
-	Includes the following customizations:
+	Includes the following customizations for Pandoc:
 	  - Use Pandoc config files from the folder $PANDOC_DIR
 	  - Enable pandoc-citeproc for citations to references
 	  - Enable hyperlinking of citations
@@ -36,15 +39,50 @@ print_help()
 	Usage: $PROGNAME [OPTIONS] input
 
 	OPTIONS:
-		-h     Print this message and exit
-		-f     Format: one of 'note', 'beamer', or 'html'
-		-p     Preview: open viewer with xdg-open
-		-t     Base directory for temporary materials (default: ${TMP_BASE})
-		-v     Verbose: echo Pandoc command
+	  -h       Print this message and exit
+	  -v       Verbose: echo Pandoc commands
+	  -p       Toggle preview (default: true in watch mode and false otherwise)
+	  -f TYPE  Format: one of 'note', 'beamer', or 'html'
+	  -t DIR   Base directory for temporary materials in watch mode (default:
+	           ${TEMP_BASE}). When not in watch mode, output is written to cwd.
+	  -w SEC   Watch source file (every SEC seconds) and re-render if changed
 	EOF
 }
 
-note()
+render()
+{
+	local mdpath=$1
+	local outdir=$2
+	local format=$3
+	local verbose=$4
+
+	case ${format} in
+		note)
+			render_note_cmd ${mdpath} ${outdir}
+			;;
+		beamer)
+			render_beamer_cmd ${mdpath} ${outdir}
+			;;
+		html)
+			render_html_cmd ${mdpath} ${outdir}
+			;;
+		*)
+			echo "Format ${format} not recognized"
+			exit ${EXIT_BAD_FORMAT}
+			;;
+	esac
+
+	# Echo the pandoc command if verbose option was enabled
+	if [ $verbose == "true" ]; then
+		echo $CMD
+	fi
+
+	eval $CMD || {
+		exit ${EXIT_PANDOC_ERROR}
+	}
+}
+
+render_note_cmd()
 {
 	local infile=$1
 	local outdir=$2
@@ -74,7 +112,7 @@ note()
 	# Outputs: CMD, OUTFILE
 }
 
-beamer()
+render_beamer_cmd()
 {
 	local infile=$1
 	local outdir=$2
@@ -104,7 +142,7 @@ beamer()
 	# Outputs: CMD, OUTFILE
 }
 
-html()
+render_html_cmd()
 {
 	local infile=$1
 	local outdir=$2
@@ -133,13 +171,48 @@ html()
 	# Outputs: CMD, OUTFILE
 }
 
+preview()
+{
+	local file=$1
+	local verbose=$2
+	local ext=${file##*.}
+	local detached=false
+
+	case ${ext} in
+		pdf)
+			viewer_cmd="zathura ${file}"
+			detached=true
+			;;
+		html)
+			viewer_cmd="chromium ${file}"
+			;;
+		*)
+			echo "No viewer defined for extension ${ext}"
+			exit ${EXIT_NO_VIEWER}
+			;;
+	esac
+
+	if [ $verbose == "false" ]; then
+		viewer_cmd="${viewer_cmd} > /dev/null 2>&1"
+	fi
+
+	if [ $detached == "true" ]; then
+		viewer_cmd="nohup ${viewer_cmd} &"
+	fi
+
+	eval ${viewer_cmd} || {
+		echo "Viewer command failed: ${viewer_cmd}"
+		exit ${EXIT_BAD_VIEWER}
+	}
+}
+
 # ----- Begin Processing -----
 
-USE_TEMP_DIR=false
+PREVIEW_TOGGLE=false
 VERBOSE=false
 
 # Get the options
-while getopts "hf:pt:v" option; do
+while getopts "hf:pt:w:v" option; do
 	case $option in
 		h)
 			print_help
@@ -149,10 +222,13 @@ while getopts "hf:pt:v" option; do
 			FORMAT=${OPTARG}
 			;;
 		p)
-			USE_TEMP_DIR=true
+			PREVIEW_TOGGLE=true
 			;;
 		t)
 			TEMP_BASE=${OPTARG}
+			;;
+		w)
+			WATCH_INTERVAL=${OPTARG}
 			;;
 		v)
 			VERBOSE=true
@@ -172,14 +248,19 @@ fi
 # Expand to absolute path
 MDPATH=$(realpath $MDFILE)
 
-# If preview is requested, output should go to a temporary area. Grab just the
-# filename part of the path. Create a temp folder which is (almost) unique to
-# the file's absolute path and the username.
+# If watch mode is requested, output should go to a temporary area. Grab just
+# the filename part of the path. Create a temp folder which is (almost) unique
+# to the file's absolute path and the username.
 #
 # Otherwise output goes into cwd.
-if [ $USE_TEMP_DIR == "true" ]; then
+if [ -v WATCH_INTERVAL ]; then
 	HASH=$(echo "${USER}-${MDPATH}" | md5sum - | cut -d' ' -f1 | cut -c1-8)
 	OUTDIR="${TEMP_BASE}/${HASH}"
+	mkdir -p ${OUTDIR} || {
+		echo "Could not create directory ${OUTDIR}"
+		exit ${EXIT_BAD_OUTDIR}
+	}
+	trap "rm -rf ${OUTDIR}" EXIT
 else
 	OUTDIR="${PWD}"
 fi
@@ -189,48 +270,37 @@ if [ -z "$FORMAT" ]; then
 	exit ${EXIT_MISSING_FORMAT}
 fi
 
-case ${FORMAT} in
-	note)
-		note ${MDPATH} ${OUTDIR}
-		;;
-	beamer)
-		beamer ${MDPATH} ${OUTDIR}
-		;;
-	html)
-		html ${MDPATH} ${OUTDIR}
-		;;
-	*)
-		echo "Format ${FORMAT} not recognized"
-		exit ${EXIT_BAD_FORMAT}
-		;;
-esac
-
-# Echo the pandoc command if verbose option was enabled
-if [ $VERBOSE == "true" ]; then
-	echo $CMD
-fi
-
 # Change to dirname of the input file so we can use its relative path to find
 # bibliography and any other resouces.
 cd $(dirname $MDPATH)
 
-$CMD || {
-	exit ${EXIT_PANDOC}
-}
+render ${MDPATH} ${OUTDIR} ${FORMAT} ${VERBOSE}
 
-if [ -n "$TEMPDIR" ]; then
-	if [ $VERBOSE == "true" ]; then
-		xdg-open $OUTFILE
-	else
-		xdg-open $OUTFILE > /dev/null 2>&1
-	fi
+# Set preview mode based on watch interval and toggle it if requested
+[[ -v WATCH_INTERVAL ]] && PREVIEW=true || PREVIEW=false
 
-	rm -f $OUTFILE
-	rmdir $TEMPDIR
+if [[ $PREVIEW_TOGGLE == "true" ]]; then
+	[[ $PREVIEW == "true" ]] && PREVIEW=false || PREVIEW=true
 fi
 
-if [ -d "$TEMPDIR" ]; then
-	echo "Failed to remove ${TEMPDIR}"
-	return EXIT_BAD_CLEANUP
+# Open previewer if the option was given.
+if [ $PREVIEW == "true" ]; then
+	preview ${OUTFILE} ${VERBOSE}
+fi
+
+if [ -v WATCH_INTERVAL ]; then
+	THEN="$(stat -c "%Y" "${MDPATH}")"
+	while true; do
+		sleep "$WATCH_INTERVAL"
+		NOW="$(stat -c "%Y" "${MDPATH}")"
+
+		if [[ "$NOW" != "$THEN" ]]; then
+			[[ $VERBOSE == "true" ]] && echo "${MDFILE} was modified ${NOW}"
+			render ${MDPATH} ${OUTDIR} ${FORMAT} ${VERBOSE}
+			THEN="$NOW"
+		else
+			[[ $VERBOSE == "true" ]] && echo "${MDFILE} not modified"
+		fi
+	done
 fi
 
